# Generated by Django 5.1.3 on 2024-11-20 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('air_temperature', models.FloatField(blank=True, null=True)),
                ('weather', models.TextField(blank=True, null=True)),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ForecastDifference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('air_temperature', models.FloatField(blank=True, null=True)),
                ('weather', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField()),
                ('forecast', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='collector.forecast')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='forecast',
            name='settlement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='collector.settlement'),
        ),
        migrations.AddIndex(
            model_name='forecast',
            index=models.Index(fields=['time'], name='time'),
        ),
    ]
