# Generated by Django 5.1.3 on 2024-11-24 10:55

from django.db import migrations
from django.core.management import call_command

fixture = 'settlements.json'

def load_fixture(apps, schema_editor):
    call_command('loaddata', fixture, app_label='collector')

def unload_fixture(apps, schema_editor):
    model = apps.get_model("collector", "Settlement")
    model.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_fixture, reverse_code=unload_fixture)
    ]
